import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp, cp, readFile, writeFile, mkdir, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {chromium} from 'playwright';
import {serve} from '../src/server';
import {loadProduction, readFeedback, saveFeedback, inside} from '../src/project';
import {command, renderVideo} from '../src/render';

test('real browser review, live reload, feedback isolation, deterministic playback and MP4 export', {timeout: 180000}, async () => {
  const root = await mkdtemp(resolve(tmpdir(), 'zimba integration '));
  await cp('templates/show', root, {recursive: true, filter: path => !path.includes('.zimba')});
  const speech = resolve(root, 'assets/audio/test-tone'); await mkdir(speech, {recursive: true});
  await command('ffmpeg', ['-y', '-loglevel', 'error', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1', resolve(speech, 'tone.wav')]);
  await writeFile(resolve(speech, 'asset.json'), JSON.stringify({schemaVersion: 1, id: 'test-tone', name: 'Test tone', type: 'audio', description: 'Test fixture', file: 'tone.wav', duration: 1}));
  const source = resolve(root, 'episodes/pilot/scenes/arrival.ts');
  const original = (await readFile(source, 'utf8')).replace("  dot.expression(4, 'happy');", "  dot.expression(4, 'happy');\n  milo.say(3, 'test-tone', 1, 'Audio fixture');");
  await writeFile(source, original);
  const server = await serve(root, 'pilot');
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  try {
    const page = await browser.newPage({viewport: {width: 1440, height: 960}});
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(server.url); await page.waitForFunction(() => Boolean((window as any).zimbaTest));
    await page.getByRole('button', {name: 'Cast', exact: true}).count();
    assert.equal(await page.locator('.asset').count(), 5);
    const frame = (time: number) => page.evaluate(time => {const test = (window as any).zimbaTest; test.seek(time); return test.player.frame();}, time);
    const first = await frame(0); const middle = await frame(2);
    assert.notEqual(first, middle); assert.equal(await frame(0), first); assert.equal(await frame(2), middle);
    const pixelCount = await page.evaluate(() => {
      const canvas = document.querySelector('#canvas canvas') as HTMLCanvasElement;
      const data = canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height).data;
      const colors = new Set<string>();
      for (let index = 0; index < data.length; index += 400) colors.add(`${data[index]},${data[index + 1]},${data[index + 2]}`);
      return colors.size;
    });
    assert.ok(pixelCount > 20, `Canvas has only ${pixelCount} colors`);
    await mkdir('.zimba/verification', {recursive: true});
    await page.screenshot({path: '.zimba/verification/desktop.png', fullPage: true});
    await page.evaluate(() => (window as any).zimbaTest.select('milo'));
    await page.locator('#pos-x').fill('600'); await page.locator('#pos-x').dispatchEvent('change');
    await page.locator('#comment').fill('Move Milo left before the greeting.');
    await page.getByRole('button', {name: 'Save proposal'}).click();
    await page.waitForFunction(() => document.querySelector('#feedback-list')?.textContent?.includes('Move Milo left'));
    const feedback = await readFeedback(root);
    assert.equal(feedback.length, 1); assert.equal(feedback[0].proposed?.x, 600);
    assert.equal(await readFile(source, 'utf8'), original, 'UI feedback must not rewrite source');
    const production = await loadProduction(root, 'pilot');
    await assert.rejects(saveFeedback(root, {...feedback[0], id: undefined}, production));
    await assert.rejects(inside(root, '../outside'));
    const oldRevision = production.revision;
    await writeFile(source, 'export default BROKEN SYNTAX');
    await page.locator('#error-banner').waitFor({state: 'visible'});
    assert.equal(await page.locator('#canvas canvas').count(), 2, 'Last valid canvas survives errors');
    await writeFile(source, original.replace('A late delivery', 'A new delivery'));
    await page.waitForFunction(() => document.querySelector('#scene-title')?.textContent === 'A new delivery');
    assert.notEqual((await loadProduction(root, 'pilot')).revision, oldRevision);
    await assert.rejects(saveFeedback(root, {episode: 'pilot', scene: 'arrival', revision: oldRevision, frame: 0, kind: 'comment', text: 'Old preview'}, await loadProduction(root, 'pilot')), /Preview changed/);
    await page.setViewportSize({width: 390, height: 844});
    await page.screenshot({path: '.zimba/verification/mobile.png', fullPage: true});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'No horizontal overflow');
    assert.deepEqual(errors, []);
    const current = await loadProduction(root, 'pilot');
    const output = await renderVideo(root, current, server.url, 'arrival');
    const probe = JSON.parse(execFileSync('ffprobe', ['-v', 'error', '-show_streams', '-show_format', '-of', 'json', output], {encoding: 'utf8'}));
    const video = probe.streams.find((stream: any) => stream.codec_type === 'video');
    assert.equal(video.width, 1280); assert.equal(video.height, 720); assert.equal(video.r_frame_rate, '24/1');
    assert.ok(probe.streams.some((stream: any) => stream.codec_type === 'audio'));
    assert.ok(Math.abs(Number(probe.format.duration) - 6) < 1 / 24 + 0.01);
    const audio = execFileSync('ffmpeg', ['-v', 'error', '-i', output, '-ss', '3.2', '-t', '0.2', '-f', 's16le', '-ac', '1', 'pipe:1']);
    assert.ok(audio.some(byte => byte !== 0), 'Scheduled audio is present, not silent');
    await cp(output, '.zimba/verification/integration-arrival.mp4');
    console.log('Verified browser playback, nonblank pixels, seek determinism, feedback/source isolation, recovery, mobile sizing, and 6s 720p/24fps MP4 with audible cue.');
  } finally {await browser.close(); await server.close(); await rm(root, {recursive: true, force: true});}
});